name: backend

on:
  push:
    branches: [ master ]
    paths: [ 'backend/**', 'k8s/**', '.github/workflows/backend.yml' ]
  workflow_run:
    workflows: ["infra"]
    types: [completed]
  workflow_dispatch: {}

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER: cluster1
  K8S_NAMESPACE: default
  ECR_REPO: fastapi-app
  K8S_DIR: k8s
  BACKEND_DIR: backend

jobs:
  build-and-deploy:
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push image
        id: img
        working-directory: ${{ env.BACKEND_DIR }}
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          REGISTRY="${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
          IMAGE_URI="${REGISTRY}/${ECR_REPO}:${GITHUB_SHA}"

          docker build -t "${IMAGE_URI}" .
          docker push "${IMAGE_URI}"

          docker tag "${IMAGE_URI}" "${REGISTRY}/${ECR_REPO}:latest"
          docker push "${REGISTRY}/${ECR_REPO}:latest"


      - uses: azure/setup-kubectl@v3

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region "$AWS_REGION" --name "$EKS_CLUSTER"

      - name: Ensure deployment/service exist
        run: |
          kubectl -n "$K8S_NAMESPACE" get deploy/fastapi-deployment || kubectl apply -n "$K8S_NAMESPACE" -f ${K8S_DIR}/deployment.yaml
          kubectl -n "$K8S_NAMESPACE" get svc/fastapi-service     || kubectl apply -n "$K8S_NAMESPACE" -f ${K8S_DIR}/service.yaml

      - name: Set image
        run: |
          kubectl -n "$K8S_NAMESPACE" set image deploy/fastapi-deployment fastapi=${{ steps.img.outputs.image_uri }} --record=true

      - name: Wait for rollout (optional)
        run: |
          kubectl -n "$K8S_NAMESPACE" wait --for=condition=Available deploy/fastapi-deployment --timeout=20m
